[package]
name = "distance-metrics"
version = "0.1.0"
edition = "2021"
workspace = ".."
readme = "../README.md"

[dependencies]

[dev-dependencies]
bencher = "0.1.5"
rand = { version = "0.8", features = ["small_rng"] }

[[bench]]
name = "all"
harness = false
